// Categories
export const REQUEST_FETCH_ALL_CATEGORIES = 'REQUEST_FETCH_ALL_CATEGORIES';
export const RECEIVE_FETCH_ALL_CATEGORIES = 'RECEIVE_FETCH_ALL_CATEGORIES';
export const ERROR_FETCH_ALL_CATEGORIES = 'ERROR_FETCH_ALL_CATEGORIES';
export const ADD_CATEGORY_LOCAL = 'ADD_CATEGORY_LOCAL';
export const REMOVE_CATEGORY_LOCAL = 'REMOVE_CATEGORY_LOCAL';
export const TOOGLE_SELECT_CATEGORY = 'TOOGLE_SELECT_CATEGORY';
export const TOOGLE_SELECT_CATEGORY_ALL = 'TOOGLE_SELECT_CATEGORY_ALL';
// ARGUMENTS
export const REQUEST_FETCH_ARGUMENTS = 'REQUEST_FETCH_ARGUMENTS';
export const RECEIVE_FETCH_ARGUMENTS = 'RECEIVE_FETCH_ARGUMENTS';
export const ERROR_FETCH_ARGUMENTS = 'ERROR_FETCH_ARGUMENTS';
export const ADD_ARGUMENT_LOCAL = 'ADD_ARGUMENT_LOCAL';
export const REMOVE_ARGUMENT_LOCAL = 'REMOVE_ARGUMENT_LOCAL';
export const UPDATE_ARGUMENT_LOCAL = 'UPDATE_ARGUMENT_LOCAL';
// Dialog Add
export const TOOGLE_OPEN_DIALOG_ADD = 'TOOGLE_OPEN_DIALOG_ADD';
export const ON_NEXT_STEP_DIALOG_ADD = 'ON_NEXT_STEP_DIALOG_ADD';
export const ON_PREVIOUS_STEP_DIALOG_ADD = 'ON_PREVIOUS_STEP_DIALOG_ADD';
export const RESET_STEPS_DIALOG_ADD = 'RESET_STEPS_DIALOG_ADD';
