export const SELECT_WANT_TO_ADD = 'SELECT_WANT_TO_ADD';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const ADD_ARGUMENT = 'ADD_ARGUMENT';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const SELECT_COMPLETE_DATE = 'SELECT_COMPLETE_DATE';
export const DONE = 'DONE';
